<a href="https://colab.research.google.com/github/hyunBBB/OMG/blob/main/lesson_03_numpy_3_modules_statistics%2C_lin%2Clogspace%2C_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy modules

In [1]:
import numpy as np

ary = np.random.randn(100)
ary = [26, 28, 30, 35, 27, 31, 44]
ary = np.array(ary)
ary

array([26, 28, 30, 35, 27, 31, 44])

#### Statistics modules
    - max, min, median, mean, std, var
    - cov, corrcoef

In [2]:
np.max(ary), np.min(ary), np.mean(ary), np.var(ary), np.std(ary)

(44, 26, 31.571428571428573, 33.38775510204081, 5.778213833187624)

최대,최소,평군,편차 예?

#### linspace, logspace
    - linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
    - logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [3]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### logspace
    - log10(x1)=2, log_10(x_2)=4

In [4]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

##### 2000년 최저시급과 2019년 최저시급을 가정하여 선형적 증가 추세를 보고싶다면?

In [5]:
time_00 = 1600
time_19 = 8350
np.linspace(time_00, time_19, 10)

array([1600., 2350., 3100., 3850., 4600., 5350., 6100., 6850., 7600.,
       8350.])

#### numpy random module
    - seed : 랜덤의 설정값
    - rand : 균등분포로 난수 생생
    - randn : 정규분포로 난수 생성
    - randint : 균등분포로 정수 생성
    - shuffle : 섞기
    - choice : 데이터를 특정 확률로 뽑기

##### seed

In [7]:
np.random.seed(1) # arbitaray 랑 랜덤. 랜덤 분포 안에서 뽑는거, 알비트러리는 정말 무작위. 
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

##### rand

In [8]:
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [9]:
np.random.rand(10)

array([0.4173048 , 0.55868983, 0.14038694, 0.19810149, 0.80074457,
       0.96826158, 0.31342418, 0.69232262, 0.87638915, 0.89460666])

In [10]:
np.random.rand(10)

array([0.08504421, 0.03905478, 0.16983042, 0.8781425 , 0.09834683,
       0.42110763, 0.95788953, 0.53316528, 0.69187711, 0.31551563])

##### randn

In [11]:
np.random.randn(10)

array([ 0.90159072,  0.50249434,  0.90085595, -0.68372786, -0.12289023,
       -0.93576943, -0.26788808,  0.53035547, -0.69166075, -0.39675353])

##### randint

In [12]:
x = np.random.randint(1, 10, (4, 4))
x

array([[6, 4, 7, 9],
       [1, 3, 8, 8],
       [8, 4, 1, 9],
       [8, 8, 2, 2]])

In [13]:
np.random.shuffle(x)
x

array([[8, 8, 2, 2],
       [8, 4, 1, 9],
       [6, 4, 7, 9],
       [1, 3, 8, 8]])