<a href="https://colab.research.google.com/github/hyunBBB/OMG/blob/main/lesson_01_python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 환경구성
    Anaconda 환경
    jupyter notebook

### Jupyter notebook 
    mode
        - 명령모드(esc)
        - 편집모드(셀 선택 후 enter)

In [ ]:
style
  - markdown
  - code

IndentationError: ignored

In [ ]:
단축키
  - shift + enter : 아래 셀로 내려가면서 실행
  - ctrl + enter : 현재 셀에 머무르면서 실행
  - ctrl + M D : 현재 셀 삭제 
  - a : 현재 선택된 셀 위에 새로운 셀 생성
  - b : 현재 선택된 셀 아래에 새로운 셀 생성
  - z : Undo (취소) 
  - spacebar : 현재 화면을 위로 올림

    Style
        - markdown
        - code

###magic command
 - % : 한 줄의 magic command를 동작
 - %% : 셀 단위의 magic command를 동작
 - 주요 maigc command
    - %pwd : 현재 jupyter notebook 파일의 경로
    - %ls : 현재 디렉토리의 파일 리스트 출력
    - %whos : 현재 선언된 변수들을 출력
    - %reset : 현재 선언된 변수들을 전부 삭제

In [ ]:
%pwd
%ls
%whos

sample_data/
Interactive namespace is empty.


Shell command
- jupyter notebook을 실항한 shell 환경의 명령을 사용
- 명령어 앞에 !를 붙여서 실행

이곳에는 노트를 작성하실 수 있습니다

    - 1순위
        - 2순위
            - 3순위

In [ ]:
python code

    
    단축키
        - shift+enter : 아래 셀로 내려가면서 실행
        - ctrl+enter : 현재 셀에 머무르면서 실행      
        - dd(명령모드) : 셀 삭제
        - a : 현재 선택된 셀 위에 새로운 셀 생성
        - b : 현재 선택된 셀 아래에 새로운 셀 생성
        - spacebar : 현재 화면을 위로 올림

In [ ]:
print("python")

python


#### magic command
    - % : 한 줄의 magic command를 동작
    - %% : 셀 단위의 magic command를 동작
    - 주요 magic command
        %pwd : 현재 jupyter notebook 파일의 경로
        %ls : 현재 디렉토리의 파일 리스트 출력
        %whos : 현재 선언된 변수들을 출력
        %reset : 현재 선언된 변수들을 전부 삭제

In [2]:
%pwd

'/content'

#### shell command
    - jupyter notebook을 실행한 shell 환경의 명령을 사용
    - 명령어 앞에 !를 붙여서 실행 libarary생성. 

In [4]:
!pip install simpleITK

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### 기본 문법
    - 변수 선언, 식별자, 자료형, 형변환, 연산자

#### 주석과 출력
    - 주석 : 작성한 문장 맨 앞에 #을 붙이면 주석처리(코드 설명)
    - 출력 : 셀의 마지막 문장 하나만 결과로 출력
            여러 결과나 코드 중간 변수 값을 출력하고 싶을때 print(출력물)로 작성


            여러줄의 주석은 큰따옴표를 세번쓰기-> 코드에 전혀 영향을 안 줌
            """
            안녕하세요
            """
            이런식으로

In [5]:
print("Hello Python")
# print('안녕 파이썬')
print('안녕하세요')

"""
여러줄의 주석은 세번쓰기
코드에 전혀 영향을 주지 않는다
"""

Hello Python
안녕하세요


'\n여러줄의 주석은 세번쓰기\n코드에 전혀 영향을 주지 않는다\n'

In [ ]:
"""이 안에 설명ㄹ을 쓰시면 됩니다."""

In [ ]:
# as dkddkdkdkdkdkdkdk thrhrl ajrrhtlvek # 여기는 코드의 영역이 아닙니다
# python
# easyup
# easy

In [ ]:
print("출력 예제 입니다")

출력 예제 입니다


In [ ]:
a = 10
b = 20
# print(a+b)
a + b

30

In [6]:
"""이 안에 설명을 쓰시면 됩니다."""

'이 안에 설명을 쓰시면 됩니다.'

In [7]:
for i in range(1, 11):
    """반복문 작성"""
    print(i)

1
2
3
4
5
6
7
8
9
10


for 문은 반복문
파이썬 수는 0부터 시작.
(11-1 해서 10기의 숫자가 나오는 것

    - docstring : 함수의 사용법을 설명 (단축키: shift+tab)
    - 자동완성 : 코드의 일부분만 작성하고 뒷부분을 자동으로 채워주는 기능 (단축키: tab)

In [8]:
import random # random 이라는 라이브러리를 불러오는 것.
random.randint
random.random

<function Random.random>

In [ ]:
random.randint, random.random

#### 변수 선언
    RAM 저장 공간에 값을 할당하는 행위

In [9]:
a = 10
b = 20
c = a+b
print(c)

30


In [10]:
d, e, f = 40, 50, 60
print(d, e, f)

40 50 60


In [11]:
g = h = 70
print(g, h)

70 70


In [12]:
import numpy as np # numpy 라이브러리를 불러옴 . as np는 np라고 줄여서 하고싶을 때 씀.
a = np.random.randint(0, 10,(10,10)) # 행렬의 크기가 10X10이고 값들은 0부터 9까지 
b = np.random.randint(11,20,(10,10))
print(a, "Wn", b, "Wn", a+b) # W가 아니라 그 원을 표시하는 더블우에 작대기 간 건데 그걸 쓰면 나처럼 저렇게 혼자 길게 나오는 놈 없음

[[5 8 9 6 6 5 8 4 2 8]
 [2 6 7 2 9 4 7 7 6 2]
 [4 0 6 5 0 0 9 3 6 7]
 [0 2 0 7 3 2 0 3 6 9]
 [3 4 5 3 4 5 7 8 4 0]
 [4 0 4 3 2 6 0 3 1 2]
 [5 5 2 3 0 2 0 6 1 8]
 [4 0 0 7 3 2 2 2 9 6]
 [8 2 8 7 2 2 5 1 2 5]
 [3 3 8 8 2 7 7 7 8 1]] Wn [[11 18 18 16 12 12 16 12 18 13]
 [19 12 11 17 13 16 13 16 17 18]
 [16 18 17 19 12 11 11 11 14 18]
 [12 12 18 17 16 13 12 14 11 15]
 [19 18 11 15 17 19 17 14 17 13]
 [19 18 15 12 11 19 16 14 17 11]
 [11 14 16 15 12 18 11 16 15 13]
 [17 18 11 13 15 12 13 14 18 18]
 [12 12 11 18 12 19 14 16 14 14]
 [16 15 13 15 18 16 11 19 12 19]] Wn [[16 26 27 22 18 17 24 16 20 21]
 [21 18 18 19 22 20 20 23 23 20]
 [20 18 23 24 12 11 20 14 20 25]
 [12 14 18 24 19 15 12 17 17 24]
 [22 22 16 18 21 24 24 22 21 13]
 [23 18 19 15 13 25 16 17 18 13]
 [16 19 18 18 12 20 11 22 16 21]
 [21 18 11 20 18 14 15 16 27 24]
 [20 14 19 25 14 21 19 17 16 19]
 [19 18 21 23 20 23 18 26 20 20]]


#### 식별자
    - 변수, 함수, 클래스, 모듈 등의 이름
    - 규칙
        - 소문자, 대문자, 숫자, _ (low dash / under_score)
        - 가장 앞에 숫자 사용 불가
        - 예약어 사용 불가 (def, class, int, ...) : 이미 python에서 문법적으로 정의되어 있는 식별자
        - Convention
            - snake_case : 변수, 함수
            - CamelCase : class

In [14]:
import keyword # 파이썬에서 사용되는 식별자 쭉 나옴.
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
candy_bar
LowDashError
# 이 부분 설명 안 하심.

#### 데이터 타입
    - RAM 저장 공간을 효율적으로 사용하기 위해서 저장 공간의 타입 설정
    - 동적 타이핑
        - 변수 선언 시 저장되는 값에 따라서 자동으로 타입이 설정

In [16]:
%whos # ndarray는 numpyarray임. int는 정수 음의 정수 양의 정수 0 해서 그런 숫자.
# flowtype?해서 정수 외 소수나 그런 실수들 실수!!!를 뜻
#module 라이브러리 뭐시기....

No variables match your requested type.


In [17]:
%reset # 삭제 하는 거 이거 실행시키면 숫자 업서짐.

Once deleted, variables cannot be recovered. Proceed (y/[n])? y
Don't know how to reset  #, please run `%reset?` for details
Don't know how to reset  삭제, please run `%reset?` for details
Don't know how to reset  하는, please run `%reset?` for details
Don't know how to reset  거, please run `%reset?` for details
Don't know how to reset  이거, please run `%reset?` for details
Don't know how to reset  실행시키면, please run `%reset?` for details
Don't know how to reset  숫자, please run `%reset?` for details
Don't know how to reset  업서짐., please run `%reset?` for details


In [20]:
a = 1
b = 'python'
type(a), type(b) # type 하고 뭘 치면 a = 1 이자너 그거가 뭔지를 알려줌 1은 정수니까 int뜨는거임

(int, str)

In [ ]:
%whos

Interactive namespace is empty.


In [21]:
import this
# 심플한 파이썬의 철학 # simple is the best다 이거야

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
